[supervisord]
nodaemon=true
logfile=storage/logs/supervisord.log
logfile_maxbytes = 20MB
logfile_backups=10
pidfile=storage/logs/supervisord.pid

[supervisorctl]
serverurl=unix:///tmp/supervisord.sock

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[program:php-fpm]
command=php-fpm -F
autorestart=true
priority=5
stdout_events_enabled=true
stderr_events_enabled=true

; [program:laravel-queue]
; process_name=%(program_name)s_%(process_num)02d
; command=php artisan queue:work --queue=parseAct --sleep=5 --tries=3 --timeout=60 --delay=5
; autostart=true
; autorestart=true
; numprocs=4
; redirect_stderr=true
; stdout_logfile=storage/logs/queue.log
; stopwaitsecs=3600

; [program:laravel-schedule]
; process_name=%(program_name)s_%(process_num)02d
; command=/bin/sh -c "while [ true ]; do (php artisan schedule:run --verbose --no-interaction &); sleep 60; done"
; autostart=true
; autorestart=true
; numprocs=1
; redirect_stderr=true
; stdout_logfile=storage/logs/laravel-schedule.log
; stopwaitsecs=3600

[include]
files = /etc/supervisor/conf.d/*.conf